# Important args
llm: "Qwen/Qwen2.5-3B-Instruct"
freeze_encoder: true
freeze_lang_model: true
epochs: 100
batch_size: 8
run_name: None
save_every: 10
wandb_project: "vlm-training"
resume_from_checkpoint: null

# Optimization / less important args
lr: 1e-5
num_workers: 4
penalty_weight: 5.0

# Dataset / path args
version: "v1.0-trainval"
dataroot: "/storage/ice-shared/cs8803vlm/rmineyev3/"
output_dir: "./outputs/latest"